export const types = {
    //Fetch all products 
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS',
    PRODUCT_FETCH_ERROR: 'PRODUCT_FETCH_ERROR',

    //Individual Product Types
    PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_FETCH_SUCCESS: 'PRODUCT_DETAIL_FETCH_SUCCESS',
    PRODUCT_DETAIL_FETCH_ERROR: 'PRODUCT_DETAIL_FETCH_ERROR',

    //Cart Types
    CART_ADD: 'CART_ADD',
    CART_REMOVE: 'CART_REMOVE'
}