export const types = {
    //Fetch all products 
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS',
    PRODUCT_FETCH_ERROR: 'PRODUCT_FETCH_ERROR',

    //Individual Product Types
    PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_FETCH_SUCCESS: 'PRODUCT_DETAIL_FETCH_SUCCESS',
    PRODUCT_DETAIL_FETCH_ERROR: 'PRODUCT_DETAIL_FETCH_ERROR',

    //Cart Types
    CART_ADD: 'CART_ADD',
    CART_REMOVE: 'CART_REMOVE',

    //Login Types
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOG_OUT',

    //REGISTER Types
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    //FETCH PROFILE 
    PROFILE_REQUEST: 'PROFILE_REQUEST',
    PROFILE_SUCCESSFUL: 'PROFILE_SUCCESSFUL',
    PROFILE_ERROR: 'PROFILE_ERROR',
    PROFILE_RESET: 'PROFILE_RESET',

    //Update Profile Deatils
    UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',

    //Shipping Details
    SAVE_SHIPPING_ADDRESS: 'SAVE_SHIPPING_ADDRESS',
    SAVE_PAYMENT_METHOD: 'SAVE_PAYMENT_METHOD',

    //Order Placement details
    PLACEORDER_REQUEST: 'PLACEORDER_REQUEST',
    PLACEORDER_SUCCESS: 'PLACEORDER_SUCCESS',
    PLACEORDER_ERROR: 'PLACEORDER_ERROR',

    //Fetch Order Details
    FETCHORDER_REQUEST: 'FETCHORDER_REQUEST',
    FETCHORDER_SUCCESS: 'FETCHORDER_SUCCESS',
    FETCHORDER_ERROR: 'FETCHORDER_ERROR',

    //Payment Details
    PAYMENT_REQUEST: 'PAYMENT_REQUEST',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_ERROR: 'PAYMENT_ERROR',
    PAYMENT_RESET: 'PAYMENT_RESET',

    //UserAll Order Details
    USERORDER_REQUEST: 'USERORDER_REQUEST',
    USERORDER_SUCCESS: 'USERORDER_SUCCESS',
    USERORDER_ERROR: 'USERORDER_ERROR',
    USERORDER_RESET: 'USERORDER_RESET'

}